version: '3.8'

services:
  web:
    build: .
    container_name: diavantage
    command: >
      sh -c  "python manage.py makemigrations && 
              python manage.py migrate &&
              python manage.py createsuperuser --username admin --email admin@example.com &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env

#  volumes:
#    pg_data:
